"""empty message

Revision ID: 0ed2c8fe604d
Revises: 99364d6362b6
Create Date: 2023-07-25 09:14:13.217221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ed2c8fe604d'
down_revision = '99364d6362b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=10), nullable=True))
        batch_op.drop_column('icon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', mysql.VARCHAR(collation='utf8mb3_bin', length=256), nullable=True))
        batch_op.drop_column('color')

    # ### end Alembic commands ###
