"""empty message

Revision ID: 852f594bf3fb
Revises: 7051d8ff7a0c
Create Date: 2023-08-19 16:58:27.059266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '852f594bf3fb'
down_revision = '7051d8ff7a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=True))
        batch_op.drop_column('pdf')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf', mysql.VARCHAR(collation='utf8mb3_bin', length=256), nullable=True))
        batch_op.drop_column('accepted')

    # ### end Alembic commands ###
