"""empty message

Revision ID: 99364d6362b6
Revises: c4ae6d0000bb
Create Date: 2023-07-18 16:11:18.753255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99364d6362b6'
down_revision = 'c4ae6d0000bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.alter_column('trading_type',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=20),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.alter_column('trading_type',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb3_bin', length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
