"""empty message

Revision ID: c130e3466560
Revises: cf05a36f025c
Create Date: 2023-08-04 23:37:32.440442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c130e3466560'
down_revision = 'cf05a36f025c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=64),
               type_=sa.String(length=24),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=24),
               type_=mysql.VARCHAR(collation='utf8mb3_bin', length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
